### ISSUE TITLE
Backups for Linux

### ISSUE THREAD

**Issue by robertu94** [CUCyber/hackpack#17]
Examples of how to conduct remote, periodic, automatic, incremental and full backups.

**Comment by lilyinstarlight** [comment]
rsnapshot can be used for this and I have configuration for it, but the problem is it will require doing some setting up on each host we want to backup. Basically we will either have to add ssh keys to root so that rsnapshot can automatically login or starting an rsync daemon (password protected) on each host to pull the files from.

I think looking into using Ansible is a very good idea and I believe you told me it already has incremental backup functionality built in to it.

**Comment by robertu94** [comment]
Potentially yes, I was hoping to set PermitRootLogin to No for sshd and require `sudo` escalation to get super user privileges, but yes we could probably make it work.

**Comment by robertu94** [comment]
``` yaml
---
- name: group
  group: name=admin state=present
- name: create user for backups
  user: name=flynn groups=admin ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa state=present
- name: send the newly created key
  authorized_key: user=flynn key key="{{ lookup('file', '/home/flynn/.ssh/id_rsa.pub'}}"
- name: Give flynn root privileges while running rsnapshot via sudo
  lineinfile: dest=/etc/sudoers after="root ALL=(ALL) ALL" line="flynn ALL=(ALL) /usr/local/bin/rsnapshot" validate='visudo -cf %s'
```

Something like this ought to to get you started. **disclaimer** I hadn't tested this play yet so use at your own risk.
